name: evac_drill_console
description: A web console which allows administration of the evac_drill_app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text: 3.0.0
  built_collection: 5.1.1
  built_value: 8.4.0
  cached_network_image: 3.2.1
  cloud_firestore: ^4.2.0
  collection: 1.16.0
  cupertino_icons: ^1.0.2
  easy_debounce: 2.0.1
  firebase_auth: ^4.1.4
  firebase_core: ^2.3.0
  flutter_animate: 1.0.0
  flutter_cache_manager: 3.3.0
  flutter_datetime_picker: 1.5.1
  flutter_google_places: 0.3.0
  flutter_staggered_grid_view: ^0.6.1
  flutter_svg: 0.22.0
  font_awesome_flutter: 10.1.0
  from_css_color: 2.0.0
  go_router: 3.1.0
  google_fonts: 3.0.1
  hive: ^2.2.3
  intl: 0.17.0
  json_path: 0.4.1
  json_serializable: 6.3.1
  page_transition: 2.0.4
  percent_indicator: 4.2.2
  provider: 6.0.4
  rxdart: 0.27.4
  sqflite: 2.2.0+2
  styled_divider: 1.0.4
  timeago: 3.2.2
  url_launcher: 6.1.5
  stream_transform: ^2.1.0
  package_info_plus: ^3.0.2

dependency_overrides:
  rxdart: 0.27.4

dev_dependencies:
  build_runner: 2.2.0
  built_value_generator: 8.4.0
  flutter_launcher_icons: 0.9.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: 'assets/images/app_launcher_icon.png'

flutter:
  uses-material-design: true
  assets:
    - assets/images/
